/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface LikertGridItem {
    'choices': string[];
    'showChoices': boolean;
    'subject': string;
  }
  interface LikertGridItemAttributes extends StencilHTMLAttributes {
    'choices'?: string[];
    'onInternalUpdated'?: (event: CustomEvent) => void;
    'showChoices'?: boolean;
    'subject'?: string;
  }

  interface LikertGrid {
    'choices': string[];
    'setChoices': string;
    'setSubjects': string;
    'subjects': string[];
  }
  interface LikertGridAttributes extends StencilHTMLAttributes {
    'choices'?: string[];
    'onSetup'?: (event: CustomEvent) => void;
    'onUpdated'?: (event: CustomEvent) => void;
    'setChoices'?: string;
    'setSubjects'?: string;
    'subjects'?: string[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'LikertGridItem': Components.LikertGridItem;
    'LikertGrid': Components.LikertGrid;
  }

  interface StencilIntrinsicElements {
    'likert-grid-item': Components.LikertGridItemAttributes;
    'likert-grid': Components.LikertGridAttributes;
  }


  interface HTMLLikertGridItemElement extends Components.LikertGridItem, HTMLStencilElement {}
  var HTMLLikertGridItemElement: {
    prototype: HTMLLikertGridItemElement;
    new (): HTMLLikertGridItemElement;
  };

  interface HTMLLikertGridElement extends Components.LikertGrid, HTMLStencilElement {}
  var HTMLLikertGridElement: {
    prototype: HTMLLikertGridElement;
    new (): HTMLLikertGridElement;
  };

  interface HTMLElementTagNameMap {
    'likert-grid-item': HTMLLikertGridItemElement
    'likert-grid': HTMLLikertGridElement
  }

  interface ElementTagNameMap {
    'likert-grid-item': HTMLLikertGridItemElement;
    'likert-grid': HTMLLikertGridElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
